### ISSUE TITLE
Unable to install using Nuget to a portable class library

### ISSUE THREAD

**Issue by ashlar64** [BlueRaja/Weighted-Item-Randomizer-for-C-Sharp#1]
Hello,
I wanted to check out your library and tried to install it to a portable library I have.
But I am unable to to do this with Nuget.  (I can install it to a regular .net project no problem.  I can also manually download and install it as well to my portable library.)

I am not familiar on how to set this up with Nuget.  Would another repository specifically for the .net core Weighted-Item-Randomizer need to be set up for this?

Thanks.

---Dave

**Comment by BlueRaja** [comment]
I take it you figured it out?
