### ISSUE TITLE
Modify it so that it is .Net 2 standard compatible

### ISSUE THREAD

**Issue by ashlar64** [BlueRaja/Weighted-Item-Randomizer-for-C-Sharp#3]
I really like this library.
I am wondering if it would it be possible to make this project .Net 2 standard compatible?

**Comment by BlueRaja** [comment]
It should be already.  [.Net Standard 1.0 libraries are forward-compatible with .Net Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
