### ISSUE TITLE
'Could not load file or assembly 'Weighted Randomizer Net Standard, Version=1.0.3.0

### ISSUE THREAD

**Issue by vargonian** [BlueRaja/Weighted-Item-Randomizer-for-C-Sharp#6]
Every time I try to run the sample code (or similar) after installing the package, I get this error:

System.IO.FileNotFoundException: 'Could not load file or assembly 'Weighted Randomizer Net Standard, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

**Comment by Botched135** [comment]
I get the exact same error

**Comment by Botched135** [comment]
@BlueRaja this should be solvable by renaming the AssemblyName in the project files. Tried to make a PR for it, but I was denied access

**Comment by Blm0423** [comment]
@BlueRaja Could you write here: what and how to rename. 
I have tried renaming in my .csproj file (with space - and _) and also rename the actual .dll file but without success. 
I am using NET 5. Even better would be skipping the spaces in the name.

**Comment by BlueRaja** [comment]
This should be fixed in v2.0. Please let me know if the issue still occurs.
